import { Task } from '../models/task.model';

/**
 * Options the list query supports. The service layer translates the validated
 * request query into this shape.
 */
export interface ListOptions {
  status?: Task['status'];
  q?: string;
  page: number;
  limit: number;
}

export interface ListResult {
  items: Task[];
  total: number; // total number of matching rows (ignoring pagination)
}

/**
 * Data fields that can be created. id/createdAt/updatedAt are generated by the repo.
 */
export interface NewTaskData {
  title: string;
  description: string | null;
  status: Task['status'];
  dueDate: string | null;
}

/**
 * Fields that can be updated. Only provided keys should change.
 */
export type UpdateTaskData = Partial<NewTaskData>;

/**
 * Persistence contract for tasks. The concrete implementation lives in
 * jsonFile.repository.ts. Coding to this interface keeps the service layer
 * storage-agnostic (and easy to mock in tests).
 */
export interface TaskRepository {
  list(options: ListOptions): Promise<ListResult>;
  findById(id: string): Promise<Task | null>;
  create(data: NewTaskData): Promise<Task>;
  update(id: string, data: UpdateTaskData): Promise<Task | null>;
  delete(id: string): Promise<boolean>;
}
